import Head from 'next/head';
import Landing from '../Components/Landing';

const Home = () => {
  return (
    <div>
      <Head>
        <title>Portfolio Landing Page Project</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Landing />
    </div>
  );
};

export default Home;
